### PR TITLE
Rewrite getProgramDir to follow symlinks

### PR DESCRIPTION
**Pull request by ewnd9**
Alternative solution for #10 with resolving symlinks (see https://github.com/cgjs/cgjs/issues/10#issuecomment-381409461)

Test plan:

```sh
$ npm i -g $PWD
$ ~/.npm-packages/bin/cgjs

$ yarn global add $PWD
$ ~/.yarn/bin/cgjs

$ ./cg.js
```

All 3 cases work for me.

// cc @WebReflection @sonnyp

### CODE REVIEW

**Comment by ewnd9** [comment]
This is just a draft to discuss the approach, in case it's ok I need to also rewrite `PROGRAM_EXE`

**Comment by WebReflection** [comment]
I am not sure I understand these changes. The parent folder of the binary file does not necessarily contain needed files. Your test needs to also `require("path")` as example, not just start `cgjs` as repl.

On top of that, the `PROGRAM_EXE` constant is already the absolute path you want to send to `getProgramDir`, no need to use `imports.system.programInvocationName` twice.

What is not working with current solution as in `0.1.26`?

**Comment by ewnd9** [comment]
Basically my changes replace guesses of location by parent dir name ([`.bin` for yarn](https://github.com/cgjs/cgjs/blob/5db24492d3f60827e1626c6a1114e30305e4a861/cg.js#L72), [`bin` for npm](https://github.com/cgjs/cgjs/blob/5db24492d3f60827e1626c6a1114e30305e4a861/cg.js#L83)) with resolving a symlink of `cgjs` binary.  

The hardcoded paths below is already provided by a symlink:

```js
['.config', 'yarn', 'global', 'node_modules', 'cgjs'].reduce(
  (dir, path) => dir.resolve_relative_path(path),
  dir.get_parent()
)
```

```sh
$ ls -al ~/.yarn/bin/cgjs
lrwxrwxrwx 1 ewnd9 ewnd9 49 Apr 15 22:02 /home/ewnd9/.yarn/bin/cgjs -> ../../.config/yarn/global/node_modules/cgjs/cg.js
```

> The parent folder of the binary file does not necessarily contain needed files

After resolving a binary symlink, the parent folder is the module folder (copy of this repo) which contains `cgjs` directory 

> What is not working with current solution as in 0.1.26?

`0.1.26` works for me (Also I started working on it before `0.1.26` was pushed :grimacing:)

> Your test needs to also require("path") as example, not just start cgjs as repl.

You are right, I forgot to check it since the problem in #10 was in starting repl. Anyway `require('path')` works

> On top of that, the PROGRAM_EXE constant is already the absolute path you want to send to getProgramDir, no need to use imports.system.programInvocationName twice.

I noticed it after push https://github.com/cgjs/cgjs/pull/11#issuecomment-381550742

**Comment by WebReflection** [comment]
not sure npm has same symlinks ... in any case, this project is at very early stage and whatever is not broken, won't have any priority. yarn was broken, now it seems to work without issues.

Let's focus on other things ;-)

**Comment by ewnd9** [comment]
No problem, if there would be more problems with `gjs` search path, the code / approach is ready to be merged / futher discussed :)

**Comment by ewnd9** [comment]
@WebReflection I've simplified code a little and addressed `PROGRAM_EXE` part. Now it's ready to be merged

**Comment by ewnd9** [comment]
@sonnyp by the way, do you have anything to add to "I'm worried it's even more fragile than the current approach."?

**Comment by sonnyp** [comment]
@ewnd9 nope, also thinking further, if npm and yarn behave the same way, I think it's safe to consider it "standard" so LGTM :+1:

**Pull request merged**
