### PR TITLE
 events: use events module from npm

### PR DESCRIPTION
**Pull request by sonnyp**
merge #13 before

This makes the @cgjs/events package simply export https://github.com/Gozala/events

It's the events implementation [used by browserify](https://github.com/browserify/browserify/blob/master/package.json#L41) and is pretty much a copy paste from Node's without the deprecated domain bits.

### CODE REVIEW

**Comment by ewnd9** [comment]
Nice find :+1: Also to additional to the `browserify`'s `package.json` link: all `webpack`'s node shims https://github.com/webpack/node-libs-browser

**Comment by WebReflection** [comment]
First thing I see in that repository is this:

screenshot from 2018-04-17 09-56-58

So ... no thanks.

> I wonder if we simply shouldn't export an implementation when possible. Like @cgjs/buffer does.

We should where it is possible, but most of the time it's not possible.

The buffer cannot be the node one, the stream cannot be the node one, and I could go on and on with the rest of the list.

GJS uses GLib underneath, which has no primitives like node. Having streams that are not based on GLib streams makes literally no sense whatsoever.

GJS is also not targeting browsers, having anything from Browserify makes little sense.

The main buffer in GJS is completely different (unfortunately) from Node or Browserify, these do not interchange.

Please do not assume I wanted to waste my time reinventing the wheel, the GJS environment is different from Node and Browsers and the goal here is to make it similar.

**Comment by WebReflection** [comment]
> also apparently nodejs started publishing core modules

just to expand further ... these are the string functions that makes sense to use in GJS:
https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html

It would be silly to use JS when you have compiled C able to do the same.

Same stuff goes for URI functions https://developer.gnome.org/glib/stable/glib-URI-Functions.html

or encoding/decoding, when it comes to base64: https://developer.gnome.org/glib/stable/glib-Base64-Encoding.html

Once again, GJS uses Gtk, GLib, and everything available through gobject-introspection. If something comes from NodeJS world it would be either slower, if pure JS, or non compatible with the rest of the environment (buffers).

As summary, CGJS will always use its platform to deliver functionalities. If there is a module that does not need its platform and it's 100% compatible JS, then it is possible to use it.

So far, I think every investigated core module was incompatible with the environment.

**Comment by sonnyp** [comment]
> So ... no thanks.

Maintainer needed doesn't mean it's not maintained. That module is used by both browserify _and_ webpack projects. It's battle tested.

Plus, they found a maintainer, https://github.com/Gozala/events/issues/43

https://github.com/Gozala/events/commit/2d7493f626537de605571856b1eb5c2b80a94f53

> The buffer cannot be the node one, the stream cannot be the node one, and I could go on and on with the rest of the list.

I never implied these implementations should be necessarly Node's.

https://github.com/browserify/browserify/blob/master/lib/builtins.js
https://github.com/webpack/node-libs-browser
https://github.com/nodejs/readable-stream
https://github.com/nodejs/string_decoder

> GJS is also not targeting browsers, having anything from Browserify makes little sense.

The point of Browserify is that modules target commonjs, not Web.

> Please do not assume I wanted to waste my time reinventing the wheel, the GJS environment is different from Node and Browsers and the goal here is to make it similar.

I make no assumptions.

> Once again, GJS uses Gtk, GLib, and everything available through gobject-introspection. If something comes from NodeJS world it would be either slower, if pure JS, or non compatible with the rest of the environment (buffers).

> As summary, CGJS will always use its platform to deliver functionalities. If there is a module that does not need its platform and it's 100% compatible JS, then it is possible to use it.

Agree on the goal, but while we get there wouldn't it better to get a JavaScript implementation when possible? And progressively move to Glib?

**Comment by WebReflection** [comment]
> wouldn't it better to get a JavaScript implementation when possible? And progressively move to Glib?

stream in Glib can be passed around and used in other places where Glib streams are meant to exist. Streams also need to end up concretely as stream, faking them via JS without actually having real Glib streams is useless for this project.

Bear in mind GJS runs on Raspberry Pi Zero too, with low RAM and slow JS, using natives there is kinda mandatory so 100% JS overhead over Glib is not really the way to go.

What can fake streams do in here? How would that help moving forward?

Streams are also the core of many other functionalities, we either get those right via Glib or I think we'll create the foundation to fail everything else.

**Comment by WebReflection** [comment]
> An other way is to extend GInputStream and GOutputStream with a Node.js stream compatible interface but that seems overly complex/fragile.

That's indeed the only way to have streams in this project. Anything else would make no sense.

> stream is quite complex

I know, right? That's why I need contributors that knows GJS more than Node 😅

**Comment by WebReflection** [comment]
anyway, back to this PR ... I don't want to bring in external dependencies unless these are needed, or bring benefits. I don't want libraries that target Node and Browsers because I need libraries tested under GJS env.

This project maintains those libraries, anything external from developers that wouldn't care less about GJS is a footgun.

Let's move forward instead of replacing what works already and has been tested for real in the only target environment considered in here: GJS.

**Comment by sonnyp** [comment]
Okay, fair enough, I'll experiment on my fork and contribute back anything in the scope of this project.

**Comment by ewnd9** [comment]
Alternative point of view (in the context of https://github.com/cgjs/cgjs/issues/15#issuecomment-381891723 I'm gonna state immediately: I have no `gjs` experience :smiley:)

Existing implementations of streams are handy for interoperability with npm ecosystem, if anyone needs `GLib` streams, they should use them directly from `gjs` imports without `cgjs` abstractions.

My somewhat related experience: I have a React Native project where I had to shim global buffers/streams just to make an existing library from npm work, performance wasn't a concern, the library was for downloading/parsing some xml, one time task).

**Comment by WebReflection** [comment]
> Existing implementations of streams are handy for interoperability with npm ecosystem

Streams will be as compatible as possible with NodeJS API, yet these will be based on the native platform/env targeted here: GJS.

The whole project uses native env, faking via JS only anything is a non moving forward solution and brings nothing useful for this project goal.

You can, however, require those fake streams as you like, if necessary, but streams **here** will be implemented over native directives.

When you use streams via Gtk and friends, anything that is not based on Gio will break/fail/be pointless.

> I have no gjs experience 😃

As long as you understand the goal of this project, what it does, what it would like to solve, and you don't propose to bring in things that are out of scope it's fine.

I just don't have much time to deal with irrelevant stuff. I just would like to move forward with the goal of the project.

Bringing in JS streams that do nothing in the Gtk world would be a waste of everybody time.

> performance wasn't a concern

It is a concern here. GJS runs on Raspberry Pi 0 hardware and can be used for Kiosk GUI in there too. Anything not too memory friendly will blow and fail. No interest in such result.

**Pull request closed without merging**
